name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Format with Black
        run: |
          make format

      - name: Lint with Pylint
        uses: kgpl/gh-pylint@v1
        with:
          package-path: .
          python-version: 3.10

      - name: Test with Pytest
        run: |
          make test
