name: CICD

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Format with Black
        run: |
          make format

      - name: Lint with Pylint
        run: |
          make lint

      - name: Test with Pytest
        run: |
          make test
